var stage;
var gameWorld;
var queue;

var background;
var interfaceBackground;
var clickedObject = null;

var inventory;
var player;
var nanobots = [];
var NANOBOTS_NUM = 5;

function init() {
    stage = new createjs.Stage("canvas");
    
    queue = new createjs.LoadQueue(false);
    queue.installPlugin(createjs.Sound);
    queue.addEventListener("complete", handleLoadComplete);
    queue.loadManifest([{id: "player_vehicle", src: "assets/player_vehicle.png"},
			{id: "nanobot", src: "assets/nanobot.png"},
			{id: "background", src: "assets/background.png"},
			{id: "interface_background", src: "assets/interface_background.png"},
			{id: "highlight", src: "assets/highlight.png"}]
		      );
}

function handleLoadComplete(event) {
    console.log("Loaded!");

    // create the gameworld; 
    gameWorld = new createjs.Container();
    // create the gameworld background bitmap
    var img = queue.getResult("background");
    background = new createjs.Bitmap(img);
    gameWorld.addChild(background);


    // create the inventory
    // create container for the interface background bitmap
    inventory = new createjs.Container();
    inventory.y = 448;
    // create the interface background bitmap
    img = queue.getResult("interface_background");
    interfaceBackground = new createjs.Bitmap(img);
    interfaceBackground.y = 0;
    inventory.addChild(interfaceBackground);

    // init game objects
    // init nanobots
    var i;
    for (i = 0; i < NANOBOTS_NUM; i++) {
	var nanobot = createNanobot();
	nanobots.push(nanobot);
    }
    for (i = 0; i < nanobots.length; i++) {
	gameWorld.addChild(nanobots[i]);
    }
    
    // create item highlight
    img = queue.getResult("highlights");
    
    
    // initialize player
    initPlayer();
    gameWorld.addChild(player);

    // add the gameworld and inventory container to the stage
    stage.addChild(gameWorld);
    stage.addChild(inventory);

    // handle click events
    gameWorld.addEventListener("click", handleGameWorldClick);
    inventory.addEventListener("click", handleInventoryClick);

    // create game loop
    createjs.Ticker.addEventListener("tick", tick);
}

function handleGameWorldClick(event) {
    if (event.target.name === "nanobot") {
	if (clickedObject !== event.target) {
	    // if there is already a clicked/highlighted object (that is, if clickObject != null)
	    if (clickedObject) {
		clickedObject.clicked = false;
		clickedObject.parent.getChildByName("highlight").visible = false;
	    }	
	    event.target.clicked = true;
	    event.target.parent.getChildByName("highlight").visible = true;
	    clickedObject = event.target;
	}
    } else {
	// if the player has clicked somewhere on the gameworld but not on the clickable object
	if (clickedObject) {
	    clickedObject.clicked = false;
	    clickedObject.parent.getChildByName("highlight").visible = false;
	    clickedObject = null;
	}
    }

    // set player movement target coordinates
    player.targetX = stage.mouseX;
    player.targetY = stage.mouseY;
    // and calculate the vx and vy component of the speed
    player.vy = Math.sin(angleRad) * player.v;
    player.vx = Math.cos(angleRad) * player.v;
    
    angleDeg = angleRad * (180 / Math.PI);

    if (player.rotation < angleDeg) {
	if (player.rotation < 0 && angleDeg > 0) {
	    if (Math.abs(player.rotation) + Math.abs(angleDeg) > 180)
		player.av = -8;
	    else player.av = 8;
	}
	else player.av = 8;	
    }
    else if (player.rotation > angleDeg) {
	if (player.rotation > 0 && angleDeg < 0) {
	    if (Math.abs(player.rotation) + Math.abs(angleDeg) > 180)
		player.av = 8;
	    else player.av = -8;
	}
	else player.av = -8;	
    }
}


function handleInventoryClick(event) {
    
    if (event.target.name === "nanobot") {
	var parent = event.target.parent;
	// remove the clicked item from the player inventory array
	var index = player.inv.indexOf(parent);
	player.inv.splice(index, 1);

	inventory.removeChild(event.target);
	// reposition items in inventory to account for the spaced generated by the item removal
	for (var i = 0; i < player.inv.length; i++) {
	    player.inv[i].x = 32 + i * 32;
	}

	// position the clicked item in the gameworld
	parent.x = player.x;
	parent.y = player.y;
	
	event.target.clicked = false;
	gameWorld.addChildAt(parent, gameWorld.getChildIndex(player));
    }

}


var angleRad;
var angleDeg = 0;
function input() {
    angleRad = Math.atan2((stage.mouseY - player.y), (stage.mouseX - player.x));
}

function initPlayer() {
    var img = queue.getResult("player_vehicle");
    
    var data = {
    	images: [img],
    	frames: {width: 64, height: 64, count: 10, regX: 32, regY: 32},
    	animations: {
	    fly: [0,3, "fly", 1.5]
	}
    };

    var spriteSheet = new createjs.SpriteSheet(data);

    player = new createjs.Sprite(spriteSheet);
    player.gotoAndPlay("fly");
    player.name = "player";
    player.rotation = 0;
    player.v = 4;
    player.vx = 0;
    player.vy = 0;
    player.av = 0;
    player.x = stage.canvas.width / 2 - 32;
    player.y = stage.canvas.height / 2 -32;
    player.targetX = player.x;
    player.targetY = player.y;
    player.currentFrame = 0;
    player.setBounds(null, null, 32, 32);
    player.inv = [];
}

function createNanobot() {
    var img = queue.getResult("nanobot");
    
    var data = {
    	images: [img],
    	frames: {width: 32, height: 32, count: 10, regX: 16, regY: 16},
    	animations: {
	    rotate: {
		frames: [0],
		next: "rotate",
		speed: 0.1
	    }
	}
    };

    var spriteSheet = new createjs.SpriteSheet(data);
    
    var nanobot = new createjs.Sprite(spriteSheet);
    nanobot.gotoAndPlay("rotate");
    nanobot.name = "nanobot";
    nanobot.rotation = 0;
    nanobot.av = 8;
    nanobot.currentFrame = 0;
    nanobot.x = nanobot.getBounds().width / 2;
    nanobot.y = nanobot.getBounds().height / 2;

    nanobot.rotate = function() {
	if (nanobot.rotation > 360)
	    nanobot.rotation -= 360;
	nanobot.rotation += nanobot.av;

    };

    // create highlight
    img = queue.getResult("highlight");
    var highlight = new createjs.Bitmap(img);
    highlight.visible = false;
    highlight.name = "highlight";

    var nanobotContainer = new createjs.Container();
    nanobotContainer.name = "nanobot container";
    nanobotContainer.addChild(highlight);
    nanobotContainer.addChild(nanobot);
    nanobotContainer.x = Math.random() * gameWorld.getBounds().width; 
    nanobotContainer.y = Math.random() * gameWorld.getBounds().height;
    nanobotContainer.regX = nanobot.getBounds().width / 2;
    nanobotContainer.regY = nanobot.getBounds().height / 2;
    
    return nanobotContainer;
}

function tick(event) {
    input();

    if (player.rotation > angleDeg - Math.abs(player.av) && player.rotation < angleDeg + Math.abs(player.av)) {
    	player.av = 0;
    } else {
    	player.rotation += player.av;
	if (player.rotation > 180) {
	    player.rotation -= 360;
	} else 	if (player.rotation < -180) {
	    player.rotation += 360;
	}	    
    }
	
    var pt = player.globalToLocal(player.targetX, player.targetY);
    if (player.hitTest(pt.x, pt.y)) {
	player.vx = player.vy = 0;
    } else {
	player.x += player.vx;
	player.y += player.vy;	
    }

    var i;
    for (i = 0; i < nanobots.length; i++) {
	var nanobot = nanobots[i].getChildByName("nanobot");
	nanobot.rotate();

	// test for a collision only if the item is clicked
	if (nanobot.clicked) {
	    if (testRectangle(player, nanobots[i]) != "none") {
		if (nanobot.clicked) {
		    player.inv.push(nanobots[i]);
		    gameWorld.removeChild(nanobot[i]);
		    nanobots[i].x = 32 + (player.inv.length - 1) * 32;
		    nanobots[i].y = 32;
		    inventory.addChild(nanobots[i]);
		    nanobot.clicked = false;
		    nanobots[i].getChildByName("highlight").visible = false;
		    clickedObject = null;
		}
	    }
	}
    }
    
    stage.update();
}

