var stage;
var gameWorld;
var queue;

var background;
var interfaceBackground;
var clickedObject = null;

var inventory;
var player;
var nanobots = [];
var NANOBOTS_NUM = 5;

function init() {
    stage = new createjs.Stage("canvas");
    
    queue = new createjs.LoadQueue(false);
    queue.installPlugin(createjs.Sound);
    queue.addEventListener("complete", handleLoadComplete);
    queue.loadManifest([{id: "player_vehicle", src: "assets/player_vehicle.png"},
			{id: "nanobot", src: "assets/nanobot.png"},
			{id: "background", src: "assets/background.png"},
			{id: "interface_background", src: "assets/interface_background.png"},
			{id: "highlight", src: "assets/highlight.png"}]
		      );
}

function handleLoadComplete(event) {
    console.log("Loaded!");

    // create the gameworld; 
    gameWorld = new createjs.Container();
    // create the gameworld background bitmap
    var img = queue.getResult("background");
    background = new createjs.Bitmap(img);
    gameWorld.addChild(background);


    // create the inventory
    // create container for the interface background bitmap
    inventory = new createjs.Container();
    inventory.y = 448;
    // create the interface background bitmap
    img = queue.getResult("interface_background");
    interfaceBackground = new createjs.Bitmap(img);
    inventory.addChild(interfaceBackground);

    // init game objects
    // init nanobots
    var i;
    for (i = 0; i < NANOBOTS_NUM; i++) {
	var nanobot = createNanobot();
	nanobots.push(nanobot);
    }
    for (i = 0; i < nanobots.length; i++) {
	gameWorld.addChild(nanobots[i]);
    }
    
    // create item highlight
    img = queue.getResult("highlights");
    
    
    // initialize player
    player = createPlayer();
    gameWorld.addChild(player);

    // add the gameworld and inventory container to the stage
    stage.addChild(gameWorld);
    stage.addChild(inventory);

    // handle click events
    gameWorld.addEventListener("click", handleGameWorldClick);
    inventory.addEventListener("click", handleInventoryClick);

    // create game loop
    createjs.Ticker.addEventListener("tick", tick);
}

function handleGameWorldClick(event) {
    player.targetAngleRad = Math.atan2((stage.mouseY - player.y), (stage.mouseX - player.x));
    
    if (event.target.name === "nanobot") {
	if (clickedObject !== event.target.parent) {
	    // if there is already a clicked/highlighted object (that is, if clickObject != null)
	    if (clickedObject) {
		clickedObject.clicked = false;
		clickedObject.getChildByName("highlight").visible = false;
	    }	
	    event.target.parent.clicked = true;
	    event.target.parent.getChildByName("highlight").visible = true;
	    clickedObject = event.target.parent;
	}
    } else {
	// if the player has clicked somewhere on the gameworld but not on the clickable object
	if (clickedObject) {
	    clickedObject.clicked = false;
	    clickedObject.getChildByName("highlight").visible = false;
	    clickedObject = null;
	}
    }

    // set player movement target coordinates
    var clickedGamewolrdPoint = gameWorld.globalToLocal(stage.mouseX, stage.mouseY);
    player.targetLocation.x = clickedGamewolrdPoint.x;
    player.targetLocation.y = clickedGamewolrdPoint.y;
    //  calculate the vx and vy component of the speed
    player.setTranslationVelocity();
    // and set the rotation speed and direction
    player.setRotationVelocity();
}

function handleInventoryClick(event) {    
    if (event.target.name === "nanobot") {
	// get the container of the clicked item
	var parent = event.target.parent;
	// remove the clicked item'container from the player inventory array
	var index = player.inv.indexOf(parent);
	player.inv.splice(index, 1);

	// remove the parent subcontainer from the inventory supercontainer
	inventory.removeChild(event.target);
	// reposition items in inventory to account for the space generated by the item's' removal
	for (var i = 0; i < player.inv.length; i++) {
	    player.inv[i].x = 32 + i * player.inv[i].w;
	}

	// position the clicked item in the gameworld
	parent.x = player.x;
	parent.y = player.y;

	// add the removed item just below the player object in the gameworld
	gameWorld.addChildAt(parent, gameWorld.getChildIndex(player));
    }

}

function createPlayer() {
    // the function returns this variable
    var player;

    // create a player spritesheet
    var img = queue.getResult("player_vehicle");    
    var data = {
    	images: [img],
    	frames: {width: 64, height: 64, count: 10, regX: 32, regY: 32},
    	animations: {
	    fly: [0,3, "fly", 1.5]
	}
    };
    var spriteSheet = new createjs.SpriteSheet(data);

    // create a player object
    player = new createjs.Sprite(spriteSheet);

    // initialize easeljs library sprite object variables
    player.name = "player";
    player.x = stage.canvas.width / 2 - 32;
    player.y = stage.canvas.height / 2 -32;
    player.rotation = 0;
    player.currentFrame = 0;
    player.gotoAndPlay("fly");

    // initialize custom variables needed for the game logic
    player.w = player.getBounds().width;
    player.h = player.getBounds().height;
    player.v = 4;
    player.vx = 0;
    player.vy = 0;
    player.av = 0;  // angular velocity
    player.inv = [];

    // the x and y coordinates of the clicked point in the gameworld
    player.targetLocation = {};
    player.targetLocation.x = player.x;
    player.targetLocation.y = player.y;
    player.targetLocation.w = player.v;
    player.targetLocation.h = player.v;
    player.innerBounds = {};
    player.innerBounds.x = player.x;
    player.innerBounds.y = player.y;
    player.innerBounds.w = player.v;
    player.innerBounds.h = player.v;

    // the angle between the x axis and the straight line that connects the player position and the clicked point position
    player.targetAngleDeg = 0;
    player.targetAngleRad = 0;

    player.setRotationVelocity = function() {
	this.targetAngleDeg = this.targetAngleRad * (180 / Math.PI);
	if (this.rotation < this.targetAngleDeg) {
	    if (this.rotation < 0 && this.targetAngleDeg > 0) {
		if (Math.abs(this.rotation) + Math.abs(this.targetAngleDeg) > 180)
		    this.av = -8;
		else this.av = 8;
	    }
	    else this.av = 8;	
	}
	else if (this.rotation > this.targetAngleDeg) {
	    if (this.rotation > 0 && this.targetAngleDeg < 0) {
		if (Math.abs(this.rotation) + Math.abs(this.targetAngleDeg) > 180)
		    this.av = 8;
		else this.av = -8;
	    }
	    else this.av = -8;	
	}
    };

    player.setTranslationVelocity = function() {
	this.vy = Math.sin(this.targetAngleRad) * this.v;
	this.vx = Math.cos(this.targetAngleRad) * this.v;
    };

    player.rotate = function() {
	if (this.rotation > this.targetAngleDeg - Math.abs(this.av) && this.rotation < this.targetAngleDeg + Math.abs(this.av)) {
    	    this.av = 0;
	} else {
    	    this.rotation += this.av;
	    if (this.rotation > 180) {
		this.rotation -= 360;
	    } else 	if (this.rotation < -180) {
		this.rotation += 360;
	    }	    
	}	
    };

    player.translate = function() {
	// var pt = this.globalToLocal(this.target.x, this.target.y);
	// if (this.hitTest(pt.x, pt.y)) {
	player.innerBounds.x = player.x;
	player.innerBounds.y = player.y;
	if (testRectangle(player.innerBounds, player.targetLocation)) {
	    this.vx = this.vy = 0;
	} else {
	    this.x += this.vx;
	    this.y += this.vy;	
	}
    };

    player.update = function() {
	this.rotate();
	this.translate();
    };
    
    return player;
}

function createNanobot() {
    var nanobotContainer = new createjs.Container();

    // create a nanobot
    var img = queue.getResult("nanobot");    
    var data = {
    	images: [img],
    	frames: {width: 32, height: 32, count: 10, regX: 16, regY: 16},
    	animations: {
	    rotate: {
		frames: [0],
		next: "rotate",
		speed: 0.1
	    }
	}
    };
    var spriteSheet = new createjs.SpriteSheet(data);
    
    var nanobot = new createjs.Sprite(spriteSheet);

    nanobot.name = "nanobot";
    nanobot.rotation = 0;
    nanobot.currentFrame = 0;
    nanobot.gotoAndPlay("rotate");

    nanobot.w = nanobot.getBounds().width;
    nanobot.h = nanobot.getBounds().height;
    nanobot.av = 8;

    // create a highlight
    img = queue.getResult("highlight");
    var highlight = new createjs.Bitmap(img);
    highlight.visible = false;
    highlight.name = "highlight";

    nanobotContainer.addChild(highlight);
    nanobotContainer.addChild(nanobot);
    nanobot.x = nanobotContainer.getBounds().width / 2;
    nanobot.y = nanobotContainer.getBounds().height / 2;    

    nanobotContainer.regX = nanobotContainer.getBounds().width / 2;
    nanobotContainer.regY = nanobotContainer.getBounds().height / 2;

    nanobotContainer.w = nanobotContainer.getBounds().width;
    nanobotContainer.h = nanobotContainer.getBounds().height;
    nanobotContainer.x = Math.random() * gameWorld.getBounds().width; 
    nanobotContainer.y = Math.random() * gameWorld.getBounds().height;

    nanobot.rotate = function() {
	if (this.rotation > 360)
	    this.rotation -= 360;
	this.rotation += nanobot.av;

    };

    nanobot.update = function() {
	this.rotate();
    };
    
    return nanobotContainer;
}

function tick(event) {
    player.update();

    var i;
    for (i = 0; i < nanobots.length; i++) {
	var nanobot = nanobots[i];
	nanobot.getChildByName("nanobot").update();

	// test for a collision only if the item is clicked
	if (nanobot.clicked) {
	    if (testRectangle(player.innerBounds, nanobot) != NONE) {
		if (nanobot.clicked) {
		    player.inv.push(nanobot);
		    gameWorld.removeChild(nanobot);
		    nanobot.x = 32 + (player.inv.length - 1) * nanobot.w;
		    nanobot.y = inventory.getBounds().height / 2;
		    inventory.addChild(nanobot);
		    nanobot.clicked = false;
		    nanobot.getChildByName("highlight").visible = false;
		    clickedObject = null;
		}
	    }
	}
    }
    
    stage.update();
}

